name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/malirezai/index.json
      env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}        
          
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Build solution and generate NuGet package
      run: dotnet pack -c Release -o out
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./out/*.nupkg --skip-duplicate --no-symbols true --api-key NUGET_AUTH_TOKEN
